name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read    # Required to read repository contents
      pages: write      # Required to deploy GitHub Pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .  # Upload everything in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
